### ISSUE TITLE
About the issue with SonyNWDestTool.

### ISSUE THREAD

**Issue by HELLSNAKES** [pamaury/rockbox#1]
### Hello Pamary, it seems like you have been inactive on the Rockbox side for a while, but I still hope you can assist me with SonyNWDestTool.
I am using SonyNWDestTool to change from Japanese to English, but it is showing the following error:  **_Can not read 'shp'_**
![image](https://github.com/pamaury/rockbox/assets/63496374/7da90536-b4c8-4582-a899-1ec538e21987)

I tried the command "help" and it produced the following output:

```
Model ID: 0x1000000
Raw device info:
 44 45 56 49 4e 46 4f 80 00 00 00 00 00 00 00 00 DEVINFO.........
 53 4f 4e 59 20 20 20 20 4e 57 2d 53 36 31 35 46 SONY    NW-S615F
 20 20 20 20 20 20 20 20 31 2e 30 30 30 30 20 20         1.0000
 20 20 32 47 35 30 36 36 36 33 35 00 00 00 00 00   2G5066635.....
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
Vendor identification: SONY
Product identification: NW-S615F
Product revision: 1.00
Product sub revision: 00
Storage size:   2G
Serial number: 5066635
Vendor specific:
An error occured during request

```

**Comment by jasa-earth** [comment]
hi hellsnakes, Im also running into this issue, with my sony nw-a829. Did you ever find a fix for this?

**Comment by HELLSNAKES** [comment]
@jasa-earth I contacted the admins on the Rockbox IRC forum, and they said that the software is too old to be fixed.
[IRC LOGS](https://www.rockbox.org/irc/log-20230824)
